Traceback (most recent call last):
  File "../pretrained_main_subset_random_choosen_experiment.py", line 748, in <module>
    main()
  File "../pretrained_main_subset_random_choosen_experiment.py", line 128, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/home/junzhin/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/junzhin/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/home/junzhin/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/junzhin/anaconda3/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/home/junzhin/Project/Summer_project/code/version1.0/pretrained_main_subset_random_choosen_experiment.py", line 487, in main_worker
    acc1 = validate(val_loader, model, criterion, args, epoch, classes_dict = classes_dict)
  File "/home/junzhin/Project/Summer_project/code/version1.0/pretrained_main_subset_random_choosen_experiment.py", line 602, in validate
    print(target.item())
ValueError: only one element tensors can be converted to Python scalars

