Namespace(arch='alexnet', batch_size=256, bottleneck_dim=256, center_crop=False, data='Office31', data_processing='ours', epochs=50, iters_per_epoch=1000, local=True, local_pretrained_path='/home/junzhin/Project/Summer_project/code/version1.0/pretrained_model_results/AlEX_office31masked1_newmodel_best.pth.tar', log='/home/junzhin/Project/Summer_project/code/version2.0/training_results/dann/AlEX_office31masked1/A_D', lr=0.01, lr_decay=0.75, lr_gamma=0.001, momentum=0.9, per_class_eval=False, phase='train', pretrained=True, print_freq=50, root='/home/junzhin/Project/Summer_project/code/version2.0/data/office31', seed=1, source='A', target='D', trade_off=1.0, weight_decay=0.001, workers=4)
../../../../dann_modified.py:46: UserWarning: You have chosen to seed training. This will turn on the CUDNN deterministic setting, which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
  warnings.warn('You have chosen to seed training. '
=> using pre-trained model 'alexnet'
Loading the local alexnet pretrained model weights!
Epoch: [0][   0/1000]	Time  3.39 ( 3.39)	Data  3.08 ( 3.08)	Loss   4.27 (  4.27)	Cls Acc 3.1 (3.1)	Domain Acc 23.0 (23.0)
Epoch: [0][  50/1000]	Time  6.30 ( 6.44)	Data  6.19 ( 6.32)	Loss   2.52 (  2.96)	Cls Acc 38.3 (22.9)	Domain Acc 97.1 (95.9)
Epoch: [0][ 100/1000]	Time  6.32 ( 6.48)	Data  6.21 ( 6.37)	Loss   1.97 (  2.56)	Cls Acc 48.8 (33.2)	Domain Acc 97.9 (97.2)
Traceback (most recent call last):
  File "/home/junzhin/Project/Summer_project/code/version2.0/common/utils/data.py", line 12, in __next__
    data = next(self.iter)
  File "/home/junzhin/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/junzhin/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1176, in _next_data
    raise StopIteration
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "../../../../dann_modified.py", line 405, in <module>
    main(args)
  File "../../../../dann_modified.py", line 152, in main
    lr_scheduler, epoch, args)
  File "../../../../dann_modified.py", line 207, in train
    x_t, _ = next(train_target_iter)
  File "/home/junzhin/Project/Summer_project/code/version2.0/common/utils/data.py", line 15, in __next__
    data = next(self.iter)
  File "/home/junzhin/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/home/junzhin/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()
  File "/home/junzhin/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()
  File "/home/junzhin/anaconda3/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 990, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/home/junzhin/anaconda3/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/home/junzhin/anaconda3/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/home/junzhin/anaconda3/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/home/junzhin/anaconda3/lib/python3.7/multiprocessing/connection.py", line 921, in wait
    ready = selector.select(timeout)
  File "/home/junzhin/anaconda3/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
KeyboardInterrupt
